### ISSUE TITLE
[Bug]: docker快速开发环境下自动化Package无法新增

### ISSUE THREAD

**Issue by PaRaD1SE98** [flipped-aurora/gin-vue-admin#1066]
### gin-vue-admin 版本

2.5.1

### Node 版本

v16

### Golang 版本

go 1.16

### 是否依旧存在

可以

### bug描述

按照文档：https://www.gin-vue-admin.com/docs/docker_dev 进行docker快速开发配置启动容器并初始化完成后，自动化Package无法新增。

相关日志：
2022/05/14 16:28:33 /gva-server/service/system/sys_auto_code.go:557 record not found
2022-05-14T16:28:33.317295691Z [0.934ms] [rows:0] SELECT * FROM `sys_auto_codes` WHERE package_name = "clipboard" AND `sys_auto_codes`.`deleted_at` IS NULL ORDER BY `sys_auto_codes`.`id` LIMIT 1
2022-05-14T16:28:33.318768394Z [github.com/flipped-aurora/gin-vue-admin/server]2022/05/14 - 16:28:33.318	error	/gva-server/api/v1/system/sys_auto_code.go:169	创建成功!	{"error": "open /server/service/enter.go: no such file or directory"}
2022-05-14T16:28:33.321016300Z [GIN] 2022/05/14 - 16:28:33 | 200 |   11.154076ms |      177.7.0.11 | POST     "/autoCode/createPackage"
2022-05-14T16:28:33.346814654Z [GIN] 2022/05/14 - 16:28:33 | 200 |    4.173116ms |      177.7.0.11 | POST     "/autoCode/getPackage"

**Comment by PaRaD1SE98** [comment]
我突然发现这个问题同样出现在demo网站上，不过下面是我的初始化后的config
```yaml
aliyun-oss:
  endpoint: yourEndpoint
  access-key-id: yourAccessKeyId
  access-key-secret: yourAccessKeySecret
  bucket-name: yourBucketName
  bucket-url: yourBucketUrl
  base-path: yourBasePath
autocode:
  transfer-restart: true
  root: /
  server: /server
  server-api: /api/v1/%s
  server-plug: /plugin/%s
  server-initialize: /initialize
  server-model: /model/%s
  server-request: /model/%s/request/
  server-router: /router/%s
  server-service: /service/%s
  web: /web/src
  web-api: /api
  web-form: /view
  web-table: /view
aws-s3:
  bucket: xxxxx-10005608
  region: ap-shanghai
  endpoint: ""
  s3-force-path-style: false
  disable-ssl: false
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
captcha:
  key-long: 6
  img-width: 240
  img-height: 80
casbin:
  model-path: ./resource/rbac_model.conf
cors:
  mode: whitelist
  whitelist:
  - allow-origin: example1.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
  - allow-origin: example2.com
    allow-methods: GET, POST
    allow-headers: content-type
    expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers,
      Content-Type
    allow-credentials: true
db-list:
- disable: false
  type: ""
  alias-name: ""
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
email:
  to: xxx@qq.com
  port: 465
  from: xxx@163.com
  host: smtp.163.com
  is-ssl: true
  secret: xxx
  nickname: test
excel:
  dir: ./resource/excel/
hua-wei-obs:
  path: you-path
  bucket: you-bucket
  endpoint: you-endpoint
  access-key: you-access-key
  secret-key: you-secret-key
jwt:
  buffer-time: 86400
  expires-time: 604800
  issuer: qmPlus
  signing-key: 29fd3083-5e6f-4e08-bf23-108212a8b738
local:
  path: uploads/file
mysql:
  path: 177.7.0.13
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: qmPlus
  username: root
  password: Aa@6447985
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: error
  log-zap: false
pgsql:
  path: ""
  port: ""
  config: ""
  db-name: ""
  username: ""
  password: ""
  max-idle-conns: 10
  max-open-conns: 100
  log-mode: ""
  log-zap: false
qiniu:
  zone: ZoneHuaDong
  bucket: ""
  img-path: ""
  use-https: false
  access-key: ""
  secret-key: ""
  use-cdn-domains: false
redis:
  db: 0
  addr: 127.0.0.1:6379
  password: ""
system:
  env: public
  addr: 8888
  db-type: mysql
  oss-type: local
  use-multipoint: false
  use-redis: false
  iplimit-count: 15000
  iplimit-time: 3600
tencent-cos:
  bucket: xxxxx-10005608
  region: ap-shanghai
  secret-id: xxxxxxxx
  secret-key: xxxxxxxx
  base-url: https://gin.vue.admin
  path-prefix: github.com/flipped-aurora/gin-vue-admin/server
timer:
  start: true
  spec: '@daily'
  detail:
  - tableName: sys_operation_records
    compareField: created_at
    interval: 2160h
  - tableName: jwt_blacklists
    compareField: created_at
    interval: 168h
zap:
  level: info
  format: console
  prefix: '[github.com/flipped-aurora/gin-vue-admin/server]'
  director: log
  show-line: true
  encode-level: LowercaseColorLevelEncoder
  stacktrace-key: stacktrace
  log-in-console: true

```
