### ISSUE TITLE
[Bug]: strict-whitelist 严格白名单模式下无法正常工作

### ISSUE THREAD

**Issue by Margular** [flipped-aurora/gin-vue-admin#1293]
### gin-vue-admin 版本

main

### Node 版本

v16.18.1

### Golang 版本

go 1.19.3

### 是否依旧存在

可以

### bug描述

1. config.yaml设置好cors的mode为strict-whitelist
2. Router.Use(middleware.CorsByRules())这一行开启
3. 所有的GET请求都无法正常工作，例如获取用户信息的/api/user/getUserInfo，会返回403

### 修改建议

原因是浏览器在处理GET请求的时候不会携带Origin头，导致后端拿不到这个头，修改方案或许可以设置为GET请求校验Referer?

**Comment by piexlmax** [comment]
尽快修复，感谢提交。

**Comment by andywu1998** [comment]
排查发现，后端确实在处理get请求的时候收不到Origin。
![image](https://user-images.githubusercontent.com/30118280/204340519-b45e81d3-c022-4aef-9d29-3039a533ee35.png)

用Refer可以

![image](https://user-images.githubusercontent.com/30118280/204340393-3275b548-535a-4d10-aa7b-8c56fb5c857e.png)

所以下一步我打算用Refer作为判断白名单

但Refer的原始值是"http://localhost:8081/" 原来用Origin的值是"http://localhost:8081"，前者加了一个“/”，如果不处理Refer直接用的话需要更新文档，白名单里也加上"/"



“浏览器在处理GET请求的时候不会携带Origin头”，参考：https://segmentfault.com/q/1010000021545199

**Comment by andywu1998** [comment]
@Margular 你的问题大概是白名单的配置没写对，把配置文件改成这样，其他的不动，allow-origin改成你想要的，试一下，相对于之前，allow-headers多了一些值。

```
cors:
  mode: strict-whitelist # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: http://localhost:8081
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
```

**Comment by Margular** [comment]
老哥，还是不行，就是Origin头的问题，我按照你那样配置:
```yaml
cors:
  mode: strict-whitelist # 放行模式: allow-all, 放行全部; whitelist, 白名单模式, 来自白名单内域名的请求添加 cors 头; strict-whitelist 严格白名单模式, 白名单外的请求一律拒绝
  whitelist:
    - allow-origin: http://192.168.200.1:8080
      allow-headers: Content-Type,AccessToken,X-CSRF-Token, Authorization, Token,X-Token,X-User-Id
      allow-methods: POST, GET
      expose-headers: Content-Length, Access-Control-Allow-Origin, Access-Control-Allow-Headers, Content-Type
      allow-credentials: true # 布尔值
```

然后登陆到应用后，点击个人信息页面，然后CTRL+R刷新，就能触发403请求，请求体(三个星号为打码)是:
```http
GET /api/user/getUserInfo HTTP/1.1
Host: 192.168.200.1:8080
Accept: application/json, text/plain, */*
DNT: 1
x-token: ***
User-Agent: ***
x-user-id: undefined
Referer: http://192.168.200.1:8080/
Accept-Encoding: gzip, deflate
Accept-Language: zh-CN,zh;q=0.9,en;q=0.8,zh-TW;q=0.7
Connection: close


```

收到的服务器回显是:
```http
HTTP/1.1 403 Forbidden
Access-Control-Allow-Origin: *
date: ***
content-length: 0
connection: close


```
