### ISSUE TITLE
[Bug]: new-token续签不生效

### ISSUE THREAD

**Issue by richardgong1987** [flipped-aurora/gin-vue-admin#1689]
### gin-vue-admin 版本

main

### Node 版本

v20.11.0

### Golang 版本

go1.21.6

### 是否依旧存在

可以

### bug描述

后端的中间件jwt.go文件的:
```go
c.Header("new-token", newToken)
```
这个头是永远不生效的

前端的:
```js
    if (response.headers['new-token']) {
      userStore.setToken(response.headers['new-token'])
    }

```

### 重现方式:

把配置设置成过期时间和续签时间一样的.这样就保证能每次刷新都能看到续签.
```yml
jwt:
    signing-key: cc39223e-366a-4b8e-b9e0-d8c5fdb3e138
    expires-time: 1m
    buffer-time: 1m
    issuer: qmPlus
```

然后,观察前端的这段代码是否能进来. 如果总是不进来.说明没有签约成功
```js
    if (response.headers['new-token']) {
      userStore.setToken(response.headers['new-token'])
    }

```

### 修改建议

造成不生效的原因是由于:
c.Header("new-token", newToken)

写在了c.Next()之前.

想要它生效就把c.Next()放在最后

把61行的c.Next()移动到81行.
