### ISSUE TITLE
个人页面点击头像上传文件

### ISSUE THREAD

**Issue by bypanghu** [flipped-aurora/gin-vue-admin#307]
将 web/src/view/person/person.vue文件下
```vuejs
 <el-avatar
     class="user-avatar"
      :size="160"
      :src="userInfo.headerImg"
      shape="square"
      @click.native="openChooseImg"
       ></el-avatar>
```
此区域代码改为
```vuejs
<div class="user-headpic-update" :style="{ 'background-image': 'url(' + userInfo.headerImg + ')','background-repeat':'no-repeat','background-size':'cover' }" >
       <span class="update" @click="openChooseImg">
        <i class="el-icon-edit"></i>
          重新上传</span>
 </div>

```

并在style里面添加样式
```scss
.user-headpic-update{
    width: 120px;
    height: 120px;
    line-height: 120px;
    margin: 0 auto;
    display: flex;
    justify-content: center;
    border-radius: 20px;
     &:hover{
      color: #fff;
      background: linear-gradient(to bottom, rgba(255,255,255,0.15) 0%, rgba(0,0,0,0.15) 100%), radial-gradient(at top center, rgba(255,255,255,0.40) 0%, rgba(0,0,0,0.40) 120%) #989898;
      background-blend-mode: multiply,multiply;
      .update{
        color:#fff ;
      }
    }
    .update{
      height: 120px;
      width: 120px;
      text-align: center;
      color:transparent;
    }
  }

```
