### ISSUE TITLE
[Bug]: docker部署初始化之后重启服务mysql连接拒绝

### ISSUE THREAD

**Issue by SunA0** [flipped-aurora/gin-vue-admin#846]
### gin-vue-admin 版本

latest

### Node 版本

16.13.1

### Golang 版本

go1.17.3

### 是否依旧存在

可以

### bug描述

系统 ubuntu 20.04
```
cd gin-vue-admin
sudo docker-compose up 
```
通过前端初始化了数据库
config.docker.yaml 生成了mysql的配置
```yaml
mysql:
  path: 177.7.0.13
  port: "3306"
  config: charset=utf8mb4&parseTime=True&loc=Local
  db-name: gva
  username: root
  password: Aa@6447985
  max-idle-conns: 0
  max-open-conns: 0
  log-mode: ""
  log-zap: false
```
关闭容器 在项目下重新运行
```
sudo docker-compose up
```
数据库无法连接
```
...
gva-server | [error] failed to initialize database, got error dial tcp 177.7.0.13:3306: connect: connection refused
...
```

### 修改建议

可能是mysql容器还没启动好go服务就去访问了 是否可以通过脚本的方式等待mysql完全启动后再去访问
https://github.com/vishnubob/wait-for-it
